/**
 * Progimage
 * <p> ProgImage is designed as a specialised image storage and processing engine to be used by other applications, and will (only) provide highperformance  access via its API. </p> <p> ProgImage provides a number of image processing and transformation capabilities  such as compression, rotation, a variety of filters, thumbnail creation, and masking. </p> <p> These capabilities are all delivered as a set of highperformance web-services that can  operate on images provided as data in a request, operate on a remote image via a URL,  or on images that are already in the repository. </p> 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Convert { 
    /**
     * The URL where the image is located
     */
    url: string;
    /**
     * The name of the image
     */
    filename: string;
    /**
     * The target format
     */
    to: Convert.ToEnum;
    /**
     * The original format of the image
     */
    from?: string;
}
export namespace Convert {
    export type ToEnum = 'png' | 'jpg' | 'jpeg' | 'tiff' | 'gif' | 'bmp';
    export const ToEnum = {
        Png: 'png' as ToEnum,
        Jpg: 'jpg' as ToEnum,
        Jpeg: 'jpeg' as ToEnum,
        Tiff: 'tiff' as ToEnum,
        Gif: 'gif' as ToEnum,
        Bmp: 'bmp' as ToEnum
    };
}